apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempconverter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tempconverter
  template:
    metadata:
      labels:
        app: tempconverter
    spec:
      containers:
        - name: app-container
          image: kfurjan/tempconverter:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_USER
              value: user
            - name: DB_PASS
              value: password
            - name: DB_HOST
              value: mysql-container
            - name: DB_NAME
              value: temperature
---
apiVersion: v1
kind: Service
metadata:
  name: tempconverter-service
spec:
  selector:
    app: tempconverter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
